### ISSUE TITLE
menu untuk role akses selain admin tidak muncul.

### ISSUE THREAD

**Issue by powehuda** [herurahmat/rimbun#1]
bang saya teh menemukan bug di proses penampilan navigation.

yaitu apabila user role selain admin itu tidak muncul menu navigationya.

penyebabnya karena sebagai berikut :
pada file Navigation.php program melakukan pengecekan sbb
	if(file_exists($this->navigation_file) && is_file($this->navigation_file))
apabila file itu tidak ditemukan. program tidak mereturn array nya sehingga navigasi selain admin tidak tampil.
begitu.

**Comment by herurahmat** [comment]
oo klo menunya bikin dr aplikasi ya?
Klo menu bikin manual sesuai format menu admin bisa sih. Thanks mas laporannya
sudah diperbaiki mas e69f16e82aaef0c70dde628beffcc0c959ad0a50

**Comment by powehuda** [comment]
siip bang sama-sama bang.
